#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# base cookbook
cookbook 'git', '~> 4.1.0'
cookbook 'apt', '~> 2.6.1'
# cookbook 'sudo', '~> 2.7.1'
cookbook 'locale', '~> 1.0.2' # need for postgresql


#rvm
cookbook 'rvm', '~> 0.9.2'

#nodejs
cookbook 'nodejs', '~> 2.2.0'
cookbook 'npm',
  git: 'https://github.com/soofaloofa/chef-npm-package-install'

#database
cookbook 'postgresql', '~> 3.4.18'   

#redis server
cookbook 'redisio', '~> 2.2.4'