# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d17cfbd57ff71e26a2b39bcd614f1092215ef1a6b8f2f283cc23abca736b8c00f23f0254a1e8523135ec873e84973960e2de037549b9da915b95b1a12422bcc

test:
  secret_key_base: 241c0ee35f21a11a201debb0e36a46655f0f812ee06d89a739ea6b03287f160cbd1a801995f211dbec573de38aecea19cf0a7b6962b53e12275ec2d9e687e042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
